builds:
  - binary: shepard
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
dockers:
- image: srizzling/shepard
  tag_templates:
  - '{{ .Tag }}'
  - 'v{{ .Major }}.{{ .Minor }}'
  - 'latest'
