builds:
  - binary: shepherd
    env:
      - CGO_ENABLED=0
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
dockers:
- image: quay.io/srizzling/shepherd
  tag_templates:
  - '{{ .Tag }}'
  - 'v{{ .Major }}.{{ .Minor }}'
  - 'latest'
